In [1]:
import numpy as np

def softmax(x, axis=-1):
    x_shifted = x - np.max(x, axis=axis, keepdims=True)
    exp_x = np.exp(x_shifted)
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)
def scaled_dot_product_attention(Q, K, V):
    d_k = Q.shape[-1]
    scores = np.matmul(Q, K.transpose(-1, -2)) / np.sqrt(d_k)
    attention_weights = softmax(scores, axis=-1)
    context = np.matmul(attention_weights, V)
    return attention_weights, context


if __name__ == "__main__":
    Q = np.random.randn(4, 8)  # seq_len=4, d_k=8
    K = np.random.randn(4, 8)
    V = np.random.randn(4, 8)

    attn, ctx = scaled_dot_product_attention(Q, K, V)
    print("Attention Weights:\n", attn)
    print("\nContext Vector:\n", ctx)


Attention Weights:
 [[0.1004339  0.49670024 0.08392393 0.31894194]
 [0.09716246 0.33844966 0.12471126 0.43967663]
 [0.03393452 0.14460456 0.16411578 0.65734513]
 [0.14227231 0.32747044 0.2725064  0.25775085]]

Context Vector:
 [[ 0.57659133  1.47228416 -0.76549746 -0.27041678  0.07924866  0.86765425
   0.02929923 -0.025845  ]
 [ 0.11200128  1.32638746 -0.72644543  0.18485586  0.29716669  0.58020851
   0.16388596 -0.01517893]
 [-0.46498103  1.14996799 -0.7379786   0.70233593  0.68869702  0.30393009
   0.33267748  0.02164806]
 [ 0.17513525  1.21049217 -0.74399966  0.30849322 -0.05005007  0.45134732
   0.18977509  0.09545349]]


In [2]:
import numpy as np

def softmax(x, axis=-1):
    x_shifted = x - np.max(x, axis=axis, keepdims=True)
    exp_x = np.exp(x_shifted)
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)
def scaled_dot_product_attention(Q, K, V):
    d_k = Q.shape[-1]
    scores = np.matmul(Q, K.transpose(-1, -2)) / np.sqrt(d_k)
    attention_weights = softmax(scores, axis=-1)
    context = np.matmul(attention_weights, V)
    return attention_weights, context


if __name__ == "__main__":
    Q = np.random.randn(4, 8)  # seq_len=4, d_k=8
    K = np.random.randn(4, 8)
    V = np.random.randn(4, 8)

    attn, ctx = scaled_dot_product_attention(Q, K, V)
    print("Attention Weights:\n", attn)
    print("\nContext Vector:\n", ctx)


Attention Weights:
 [[0.07625604 0.6244275  0.12912391 0.17019255]
 [0.31647279 0.14771935 0.09962091 0.43618695]
 [0.14282409 0.32032111 0.16922312 0.36763169]
 [0.28546494 0.34562975 0.13804654 0.23085878]]

Context Vector:
 [[-0.3654411  -0.67182653 -0.20158372 -0.19870041 -1.17672498 -0.9627569
   0.42214984 -0.36741707]
 [ 0.05756078  0.1543572  -0.59594482 -0.02067051 -1.11648696 -0.66520003
   0.02579407  0.01898856]
 [ 0.06067797 -0.2561193  -0.45703603 -0.21007783 -1.18490379 -0.76585041
   0.21394166 -0.23467231]
 [-0.23673929 -0.17161238 -0.30440956  0.01754444 -1.02354594 -0.71928966
   0.1485155  -0.04382055]]
